version: "3.8"

services:
  db:
    image: mysql:8
    platform: linux/amd64
    container_name: db
    # volumes:
    #   - db-store:/var/lib/mysql
    ports:
      - "3308:3308"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mnts
      - MYSQL_TCP_PORT=3308
  backend-app:
    image: alvaniev/mnts-backend
    container_name: mnts-backend
    # volumes:
    #   - static-dir:/usr/src/app/public
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - NODE_DBDIALECT=mysql
      - NODE_DBHOST=db
      - NODE_DBPORT=3308
      - NODE_DBUSER=root
      - NODE_DBPWD=root
      - NODE_DBSCHEMA=mnts
      - NODE_DBSYNC=true
      - NODE_HOST=http://localhost:3000

# volumes:
#   db-store:
#     name: db-store
#   static-dir:
#     name: mnts-static-dir